#!/bin/sh
clear
xdotol type "echo 'deb https://assets.checkra.in/debian /' | sudo tee -a /etc/apt/sources.list" && sleep 1;xdotool key Return
sleep 3
xdotool type "sudo apt-key adv --fetch-keys https://assets.checkra.in/debian/archive.key" && sleep 2;xdotool key Return
sleep 2
xdotool type "sudo apt update" && xdotool key Return
sleep 2
clear
xdotool type "sudo apt install checkra1n -y" && sleep 2;xdotool key Return
sleep 2
clear
cd $HOME
git clone https://github.com/mbusb/multibootusb
cd multibootusb
sudo chmod +x install.py
sudo ./install.py
sleep 2
cd
echo "all set on my end"
sleep 3
xdotool keydown Ctrl key +d keyup Ctrl

